config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :orders
  resources :groups
  resources :group_members
      get "group_members/:id", to: "group_members#add_friend" 
  resources :users
  authenticated :user do
    root to: 'users#home', as: :authenticated_root
  end
  root to: "start#start"
  get "start/home", to: "start#home"
  post "invited_to_orders/invite", to: "invited_to_orders#invite"
  mount ActionCable.server => '/cable'
  post "friendships/add_friend", to: "friendships#add_friend"
  post "invited_to_orders/inviteGroup", to: "invited_to_orders#inviteGroup"
  post "invited_to_orders/join", to: "invited_to_orders#join"
  post "/orders/putList", to: "orders#putList"
  post "/orders/finish", to: "orders#finish"
  post "/groups/newGroup", to: "groups#newGroup"
  # post "/user/home", to: "user#home"

  resources :order_details
  post "/group_members/delete", to: "group_members#delete"
  post "/group_members/add", to: "group_members#add"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "invited_to_orders/showInvited", to: "invited_to_orders#showInvited"
  get "invited_to_orders/showJoined", to: "invited_to_orders#showJoined"
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :user_id, uniqueness: { scope: :group_id }
end

app/controllers/group_members_controller.rb
class GroupMembersController < ApplicationController
  before_action :authenticate_user!
  def destroy
# @group = Group.find(params[:group_id])
    
    @group_member = GroupMember.find(params[:id])
    @group_member.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Group member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create
    @group = Group.find(params[:group_id])
    @group_member = @group.group_members.build(:user_id => params[:user_id],:group_id => params[:group_id] )

    if @group_member.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url

    end
  end

  def index

    @group_members = []
    @group_id = params[:id]
    @members_id = GroupMember.where(group_id: params[:id])
    @members_id.each do |member|
      friends = User.where(id: member.user_id)
      friends.each do |friend|
        @group_members.push(friend);
      end
    end
    render json: {group_members: @group_members,group_id: @group_id}



  end

  def delete

      @group_member = GroupMember.find_by(user_id: params[:id], group_id: params[:g])
      if @group_member.destroy
      respond_to do |format|
        format.json { render json: {deleted: "done"} }
        # format.json { head :no_content }
      end
    end
    
  end

  def add

    @addMember = User.find_by username: params[:memberName]
    @friends = current_user.friendships
    @found = 0
    if @addMember
      @friends.each do |friend|
        if @addMember.id == friend.friend_id
          @found = 1
          break
        end
      end
      if @found == 1
        respond_to do |format|
          puts(@addMember)
          @group = Group.find(params[:group_id])
          @group_member = @group.group_members.build(:user_id => @addMember.id,:group_id => params[:group_id] )
          if @group_member.save
            @friend = User.find_by id: @group_member.user_id
            format.json {render json: {group_member: @group_member, friend: @friend}}
          else
            flash[:error] = "Unable to add friend."
            # redirect_to root_url
            puts("ssssssssssssssssssssssssssssssssssssssssssssssssss")
          end
        end
      else
        respond_to do |format|
          format.json { render json: {'NotFriend':"not found"} }
        end
      end
    else
      respond_to do |format|
        format.json { render json: {'Alert':"not found"} }
      end
    end
  end



end

app/views/group_members/_form.html.erb
<%= form_with(model: group_member, local: true) do |form| %>
  <% if group_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group_member.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :group %>
    <%= form.text_field :group_id, id: :group_member_group_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :group_member_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/group_members/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group_member: @group_member %>

<%= link_to 'Show', @group_member %> |
<%= link_to 'Back', group_members_path %>

app/views/group_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_members.each do |group_member| %>
      <tr>
        <td><%= group_member.group.name %></td>
        <td><%= group_member.group.id %></td>
        <td><%= group_member.user.username %></td>
        <td><%= link_to 'Show', group_member %></td>
        <td><%= link_to 'Edit', edit_group_member_path(group_member) %></td>
        <td><%= link_to 'Destroy', group_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New group_member', new_group_member_path %>

app/views/group_members/new.html.erb
<h1>New Group</h1>



<%= link_to 'Back', group_members_path %>

app/views/group_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group_member.group %>
</p>



<p>
  <strong>Created By: </strong>
  <%= @group_member.user.username %>
</p>

<%= link_to 'Edit', edit_group_member_path(@group_member) %> |
<%= link_to 'Back', group_members_path %>