config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :orders
  resources :groups
  resources :group_members
      get "group_members/:id", to: "group_members#add_friend" 
  resources :users
  authenticated :user do
    root to: 'users#home', as: :authenticated_root
  end
  root to: "start#start"
  get "start/home", to: "start#home"
  post "invited_to_orders/invite", to: "invited_to_orders#invite"
  mount ActionCable.server => '/cable'
  post "friendships/add_friend", to: "friendships#add_friend"
  post "invited_to_orders/inviteGroup", to: "invited_to_orders#inviteGroup"
  post "invited_to_orders/join", to: "invited_to_orders#join"
  post "/orders/putList", to: "orders#putList"
  post "/orders/finish", to: "orders#finish"
  post "/groups/newGroup", to: "groups#newGroup"
  # post "/user/home", to: "user#home"

  resources :order_details
  post "/group_members/delete", to: "group_members#delete"
  post "/group_members/add", to: "group_members#add"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "invited_to_orders/showInvited", to: "invited_to_orders#showInvited"
  get "invited_to_orders/showJoined", to: "invited_to_orders#showJoined"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_members, dependent: :destroy

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def newGroup
    @group = Group.new(name: params['name'], user_id: current_user.id)
    @group.user_id = current_user.id
    respond_to do |format|
      if @group.save
        p @group
        format.json { render json: {group: @group} }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to '/groups', notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    # respond_to do |format|
      # format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      # format.json { head :no_content }
      render json: {msg: 'Group was successfully destroyed'}
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :user_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :group_name %>
  </div>

  <!--<div class="field">-->
  <% form.hidden_field :user_id, id: :user_id , value: :user_id%>
  <!--</div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<div>
  <div class="center-block center">
    <div>
      <input type="text" id="add_group" style="width: 50%; background: white; border: black solid" >
      <button id="add" class="add" onclick="addGroup(this)" >New Group </button>
    </div>
  </div><br><br>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4" style="border: solid black; height: 350px; overflow-y: scroll">
      <table class=" ">
        <col width="150">
        <tbody id="groupTable">
          <% @groups.each do |group| %>
            <tr style="height: 40px" >
              <td><p style="display:inline" onclick ="displayGpMember(this)" class='grpName' gid="<%= group.id %>"><%= group.name %></p></td>
              <!-- <td><% group.user.id %></td> -->
              <!-- <td><% group.id %></td> -->
              <!-- <td><% link_to 'Show', group %></td> -->
              <td><%= link_to 'Edit', edit_group_path(group) %></td>
              <td><%= link_to group, method: :delete ,data: { confirm: 'Are you sure?' } ,:remote =>true, :class => 'gp-link'  do %>
                  <i class="fa fa-times-circle"></i>
                <% end %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-6" style="border: solid black; height: 350px; overflow-y: scroll; float: right">
      <div  id="display_group" >
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <legend >Friend List</legend>
            <fieldset style="height: 330px; padding-top: 10px">
              <div  id="frindlist">
              </div>
            </fieldset>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= stylesheet_link_tag "add_friend" %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>
<p>
 <ul>
<% if @group.user.friendships.any? %>
  <% for friendship in @group.user.friendships %>
    <li>
      <%=h friendship.friend.username %>
      <%= link_to "Add as a group member", group_members_path(:user_id => friendship.friend ,:group_id => @group), :method => :post %>
   </li>
  <% end %>

<% else %>
<p>you've no friends</p>
<% end %>
</ul>
</p>

<p>
  <strong>group members:</strong>
  <% if @group.group_members.any? %>
  <% for gm in @group.group_members %>
    <li>
      <%=h gm.user.username %>
      <%= link_to "remove from group",group_member_url(gm), :method => :delete, data: { confirm: 'Are you sure?' } %>
   </li>
<% end %>
<% end %>
</p>
  <strong>User:</strong>
  <%= @group.user %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>