config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :orders
  resources :groups
  resources :group_members
      get "group_members/:id", to: "group_members#add_friend" 
  resources :users
  authenticated :user do
    root to: 'users#home', as: :authenticated_root
  end
  root to: "start#start"
  get "start/home", to: "start#home"
  post "invited_to_orders/invite", to: "invited_to_orders#invite"
  mount ActionCable.server => '/cable'
  post "friendships/add_friend", to: "friendships#add_friend"
  post "invited_to_orders/inviteGroup", to: "invited_to_orders#inviteGroup"
  post "invited_to_orders/join", to: "invited_to_orders#join"
  post "/orders/putList", to: "orders#putList"
  post "/orders/finish", to: "orders#finish"
  post "/groups/newGroup", to: "groups#newGroup"
  # post "/user/home", to: "user#home"

  resources :order_details
  post "/group_members/delete", to: "group_members#delete"
  post "/group_members/add", to: "group_members#add"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "invited_to_orders/showInvited", to: "invited_to_orders#showInvited"
  get "invited_to_orders/showJoined", to: "invited_to_orders#showJoined"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable , :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  has_many :orders, dependent: :destroy
  has_many :groups, dependent: :destroy

  has_many :group_members, dependent: :destroy

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  mount_uploader :image, ImageUploader
  has_many :invited_to_orders, dependent: :destroy
  has_many :order_details, dependent: :destroy

   def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name
      user.image = auth.info.image
    end      
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # def facebook
  #    @user = User.from_omniauth(request.env["omniauth.auth"])
  #    sign_in_and_redirect @user      
  # end
  def sign_in_with(provider_name)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user, :event => :authentication
    set_flash_message(:notice, :success, :kind => provider_name) if is_navigational_format?
  end

 def facebook
	  sign_in_with "facebook"
	end
	 def google_oauth2
	    sign_in_with "google"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [ :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
    @group = @user.groups.build
    @groups = @user.groups
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def home
    @user = current_user
    # @group = @user.groups.build
    # @groups = @user.groups
    @orders = Order.where(user_id: @user.id).order("created_at").last(10).reverse

    # Friends Activities
    @invited = InvitedToOrder.where(user_id: @user.id).order("created_at").last(10).reverse
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username , :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div>
  <p>Choose new image: </p>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<!-- About -->
<!--<div id="about" class="section ">-->

  <!-- Container -->
  <div class="container">

    <!-- Row -->
    <div class="row">

      <!-- Section header -->
      <div class="section-header text-center">
        <h2 class="title">Welcome to YallaNotlob</h2>
      </div>
      <!-- /Section header -->

      <!-- about -->
      <div class="col-md-5" style="border: solid black; height: 350px; overflow-y: scroll">
        <h4 style="padding-top: 10px">Last Orders</h4>
        <hr>
        <ul style="height: 250px; font-size: 15px">
        <% @orders.each do |order| %>
          <li style="font-size: 15px"><%= link_to order.meal, order_path(order)  %> created <%= time_ago_in_words(order.created_at) %> ago</li>
        <% end %>
        </ul>


      </div>
      <!-- /about -->

      <!-- about -->
      <div class="col-md-5" style="border: solid black; height: 350px; overflow-y: scroll;float: right" id="friends_activities">
        <h4 style="padding-top: 10px">Friends Activities</h4>
        <hr>

        <ul>

        <% @invited.each do |event| %>
            <li style="font-size: 15px"><%=  event.order.user.username %> invited you to <%= link_to 'order', order_url(event.order) %> from <%=	 event.order.resturant %><br></li>
        <%	 end %>

        </ul>
      </div>
      <!-- /about -->


    </div>
    <!-- /Row -->

  </div>
  <!-- /Container -->

<!--</div>-->
<!-- /About -->

<%= javascript_include_tag('home.js') %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<div class="col-md-10 col-md-offset-1">
<table >
  <col width="130">
  <col width="180">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <col width="180">
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag(user.image.thumb.url, alt: 'Image') if user.image? %></td>
        <td><%= user.username %></td>
        <!-- <td><%= user.id %></td> -->
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>


<%= link_to 'New User', new_user_path %>

<%= stylesheet_link_tag "orders" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <p>Image: </p> -->
<p>
  <%= image_tag(@user.image.thumb.url, alt: 'Image') if @user.image? %>
  <%= link_to 'Edit profile', edit_user_path(@user) ,{:class => 'linky' ,:style => 'color:white;' }%> 
  <%= link_to "Add friend", friendships_path(current_user) ,{:class => 'add_link' , :style => 'color:white;'}%>
</p>

<p>
  <!-- <strong>Username:</strong> -->
  <strong> <font size="18px;" color="#777777"> <%= @user.username %> </font></strong>
</p>
<br><br><br><br><br><br>
<div>
   <div class="row">
      <div class="col-md-10 col-md-offset-1">
      <fieldset style="height: 330px; background-color: white; ">
      <legend  style="background-color: white;border-color: #00ccFF;"><h2>                                          
        <p><font size="6px;" color="#3377ba"> <i class="fa fa-users"></i>Friends:</font></p></h2> </legend>

        <% for friendship in @user.friendships %>
            <div class="col-lg-4 col-sm-6 portfolio-item">
               <%= image_tag(friendship.friend.image.thumb.url, alt: 'Image') if friendship.friend.image? %>
               <%=h friendship.friend.username %>
              (<%= link_to "Unfriend", friendship, :method => :delete %>)
            <br />
            <br />
            <br />
          </div>
          <% end %>
      </fieldset>
    </div>
  </div>
</div>

<br />
<br />
<!-- <div>
   <div class="row">
      <div class="col-md-10 col-md-offset-1">
      <fieldset style="height: 330px; background-color: white; padding-top: 10px">
      <legend  style="background-color: white"><h2>Friended by: </h2></legend>
          <% for user in @user.inverse_friends %>
            <div class="col-lg-4 col-sm-6 portfolio-item">
            <%= image_tag(user.image.thumb.url, alt: 'Image') if user.image? %>
            <%=h user.username %>
            <br />
            <br />
            <br />
          </div>
          <% end %>
      </fieldset>
    </div>
  </div>
</div> -->
<!--   <br />
  <br />
<h2>groups</h2>
 <br>
 <br />
<%= link_to "show group", groups_path %>
  <br>
 <br />
<div class="col-md-12">
  <%= form_for @group, remote: true, :html => { class: 'form-horizontal', role: 'form' } do |f| %>
    <% if @group.errors.any? %>
      <div class="panel panel-danger col-md-offset-1">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@group.errors.count,"error") %>
            prohibited this group from being created
          </h2>
          <div class="panel-body">
            <ul>
              <% @group.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :body, "New group" %>
      </div>
      <div class="col-md-10">
        <%= f.text_field :name, rows: 10, class: 'form-control', placeholder: 'group name' %>
<%= f.hidden_field :user_id, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit "Add group", class: 'btn btn-primary btn-lg pull-right' %>
      </div>
    </div>
  <% end %>
</div> -->


<p style="font-size: 22px;"><i class="fa fa-backward" aria-hidden="true"></i><%= link_to 'BackHome', root_path ,{:style => 'color: #3377ba;' , :class => "back"} %></p>
<%= stylesheet_link_tag "profile" %>
<%= javascript_include_tag "jquery" %>